### ISSUE TITLE
communication Error

### ISSUE THREAD

**Issue by de-Bat** [davesmeghead/visonic#106]
Hi,
After  technician visit the panel announce a communication error. It looks like the phone connection (because it stopped alerting like temper alert)
In addition the integration cannot connect to the panel.
Is it possible that the no phone communication  causes the integration not able to connect issue?
thanks,
Ron

**Comment by davesmeghead** [comment]
Hi,
If you upload a debug log file then I'll take a look through to see if I can help
D

**Comment by de-Bat** [comment]
Hi,
Sorry for the late response
Thanks for the reply!
I'm uploading 2 files:  the second one is after i crossed the lines (tx, rx)
[visonic1.txt](https://github.com/davesmeghead/visonic/files/14840527/visonic1.txt)
[visonic2.txt](https://github.com/davesmeghead/visonic/files/14840528/visonic2.txt)
, just to be sue i did not make a mistake...
Thanks,
Ron

**Comment by davesmeghead** [comment]
Hi, I might be stating the obvious here but in both log files there is no data being received from the panel, not a single byte. I know this because of this line
```
[Controller] Visonic Plugin has suspended all operations, there is a problem with the communication with the panel (i.e. no data has been received from the panel)
```
I suggest that you try the loopback test, on the gadget you're using connect Tx and Rx together.  Whatever my integration sends it also receives and I detect this on initial connection.  Wait a few minutes then save and upload the log file, you should see loopback test messages.
If you see loopback messages in the log file then there is something wrong with the wiring to the panel or with the panel itself.  
If you do not see loopback messages then there's something wrong with the integration in Home Assistant, the wiring to the gadget (USB or Ethernet) or with the gadget itself.

**Comment by davesmeghead** [comment]
Closing this issue as over 4 months old without response, if the problem continues then either reopen or create a new issue please
