### ISSUE TITLE
Panel disconnects every 15 mins with 150+ log messages

### ISSUE THREAD

**Issue by paulh001** [davesmeghead/visonic#112]
[PowermaxLog.zip](https://github.com/davesmeghead/visonic/files/15286277/PowermaxLog.zip)

Hi Dave, as requested attached is a log file regarding the issue of my panel disconnecting every 15 mins and generating 150+ log messages.
Thanks, Paul

**Comment by davesmeghead** [comment]
Hi Paul,

I've had a look at your log file and it does indeed disconnect after about 5 minutes and then 15 minutes after that, assuming that it's not the gadget in your panel that's resetting every 15 minutes then it must be your house router.  The integration just tells me that it's a disconnection of the link so it's something external, and external to Home Assistant as well.  I'm really confused though as it can't be the router restarting or renewing leases as that takes more than the 20 seconds that it reconnects.

As for the log messages I believe that it's due to the Home Assistant more recent releases getting picky about integrations deleting and recreating entities with the same name correctly, and unfortunately in the integration I was lazy and didn't tidy up on deletion.  I believe that this is fixed in the dev version so if you have chance to try it then let me know if it works, otherwise it'll get fixed as I move the code across from dev to the main release.

Thanks for the log file
Dave

**Comment by paulh001** [comment]
Hi Dave,
Many thanks for the quick response.  I'm pretty sure it is not the router so maybe something strange with the Wemos board.  I originally had it setup for Smartthings but gave up on that reflashed it.
I'll give the dev version a go when I have some spare time.
Great integration by the way.
Paul

**Comment by davesmeghead** [comment]
Hi,
Also look at these for the log message problem, it's a known Home Assistant issue that is being worked on.
https://github.com/home-assistant/core/pull/117091
https://github.com/home-assistant/core/issues/116975

**Comment by davesmeghead** [comment]
Closing this issue, if there are further problems then please either reopen it or create a new issue.
