### ISSUE TITLE
Include USR-WIFI232-A2 in compatible module

### ISSUE THREAD

**Issue by Giuse1977** [davesmeghead/visonic#12]
Hi, first of all I want to thank you for your work!
I’ve used USR-WIFI232-A2, a cheap module with embedded antenna, and works perfectly out of the box! So if you wish you can add it in compatible module list (if not as suggested hardware) in your documentation!

**Comment by olijouve** [comment]
I've been running quite well for several months on 6~7$ ESP32 dev board and a basic Wifi2Serial sketch i had enhanced over time.

But that was before I starting to have too much interferences on 2.4Ghz band, mainly our baby phone/cam and my new neighbourg with its army of wifi repeaters :-/

I ended this mess up few days ago by switching to an USRIOT USR-TCP232-T2, which also works perfectly.

I have to find time to organise, document and share that ESP32 integration, as well as my card.

**Comment by mrnik** [comment]
Giuse1977 can you please guide me about your configuration on the USR-WIFI232-A2, I set the Network A Setting as Client and I set to work as TCP, an ip and a port. Also I set the RS232 baud rate at 9600 btu, disable control flow, no parity and 1 stop bit. The only thing I didn't do is to set it in STA mode, because after this configuration there wasn't active the Wifi server interface of the USR-WIFI232-A2 for configuration. Is there any diagnostic tool to be sure if everything is ok before test it with home assistant. Because I couldn't make a connection with home assistant yet and I want to troubleshoot everything step by step.

**Comment by Giuse1977** [comment]
Mrnik, I recently switched to the NodeMCU as per wiki, cause I got many disconnections and the USR was instable (not sure if due my router Wi-Fi issues). Btw, when I installed the USR configuration was really straightforward.. I don’t understand what you mean when you say you cannot set It to STA mode. Mine had the web interface reachable (when the module was working) after the configuration. Maybe something is wrong in this..
