### ISSUE TITLE
Alarm Panel v 9.6.5 and attributes

### ISSUE THREAD

**Issue by open1999** [davesmeghead/visonic#125]
Hello,

the panel has been modified.
You deleted attributes.

How to recover "Panel Alert In Memory" ?

I'v seen the wiki.

Dan

**Comment by davesmeghead** [comment]
There are attributes deleted but I have been careful to keep the ones needed. Alert in `memory` is part of the Attributes of the alarm control panel Entity

![image](https://github.com/user-attachments/assets/d34d6dde-b332-4f52-94e6-095839d6c6c9)

**Comment by open1999** [comment]
I found panel ready, trouble but not seen memory

thank you very much for this work and the support

**Comment by XxTopKillerzZ** [comment]
I believe [this part](https://github.com/davesmeghead/visonic/wiki#attributes-of-the-alarm-panel-entity) of the wiki is not updated yet.

Based on my alarm, PowerMax Pro Part: [PowerMax_Attributes.txt](https://github.com/user-attachments/files/16404151/PowerMax_Attributes.txt)

'Panel Status Code' does not exist
'Panel Mode' renamed to 'mode'
'Model' renamed to 'Panel Model'
'Panel Name' always unknown in my alarm
'Panel Status' renamed to 'state'
'Plugin Version' renamed to 'Client Version'
'Panel Ready' renamed to 'ready'
'Panel Alert In Memory' renamed to 'memory'
'Panel Trouble' renamed to 'trouble'
'Panel Bypass' renamed to 'bypass'
'Panel Armed' does not exist
'Panel Status Changed' does not exist
'Panel Alarm Event' does not exist
'Panel Alarm Status' renamed to 'alarm'
'Panel Trouble Status' renamed to 'trouble'
'Panel Last Event Data' does not exist


Also in my system Door Zones, Motion Zones, Smoke Zones are empty and all sensors are in 'Other Zones' attribute. Idk if it's just because of my version.

**Comment by davesmeghead** [comment]
I've gone through them properly, thanks for the prompt and the information.
I've just released to Github so give it a go.
Note that Door Zones, Motion Zones, Smoke Zones are only shown if you tick the box when setting up the config
