### ISSUE TITLE
Version 9.6.5 or 9.6.8 reload problem

### ISSUE THREAD

**Issue by open1999** [davesmeghead/visonic#126]
Hello,

Problem with Reload

If we do a reload Alarm and detector unavailable.

Solution restart HA.

![image](https://github.com/user-attachments/assets/6a34a77e-20d7-49cf-b312-5596048787c8)

Log
[home-assistant_2024-07-29T21-24-18.596Z.log.zip](https://github.com/user-attachments/files/16419302/home-assistant_2024-07-29T21-24-18.596Z.log.zip)

thanks

**Comment by davesmeghead** [comment]
From the log file I can see that...

After starting the Integration it attempts to get to Powerlink Emulation Mode but
- after 20 seconds you enter Installer Mode on the panel itself which stops Auto Enroll
- after another 20 seconds there is either an automation that reloads it or you do it manually I'm not sure. In either case you have an Error in your automation
```
2024-07-29 23:20:01.381 ERROR (MainThread) [homeassistant.components.automation.alarme_resynchro] Alarme - Resynchro: Error executing script. Invalid data for call_service at pos 1: required key not provided @ data['entity_id']
2024-07-29 23:20:01.381 ERROR (MainThread) [homeassistant.components.automation.alarme_resynchro] Error while executing automation automation.alarme_resynchro: required key not provided @ data['entity_id']
```

The above reloads the integration and at row 183 in the log file it starts again
For some reason that I don't know why, the Integration then starts to get the EPROM data again and fails twice with errors on the transfer. I'm not sure why the data transfers fail but it might be something for you to look in to.  The first time it succeeds on line 62 but then fails on lines 232 and 409. After each failure, after lines 238 and 413 it delays and then tries to download the EPROM again.

At line 450 the Integration is reloaded (with the same automation errors).
But once again it gives a failure to transfer the EPROM data (line 514)

Perhaps try restarting Home Assistant instead of reloading the Integration, it might not be resetting the USB properly somehow.  But reloading should work and I'm not sure why it's giving the errors in the data transfer.

If you experiment and find out anything else then let me know but there's not a lot more I can do to help I'm afraid.

**Comment by davesmeghead** [comment]
I'm closing this issue, any further problems then please create a new issue
