### ISSUE TITLE
V 0.9.6.17 infinite loop

### ISSUE THREAD

**Issue by open1999** [davesmeghead/visonic#133]
Hello,

if we reload the module after an hour we have an infinite loop.

My pc was crashed.
Physical restart required.

In log
[_homeassistant_logs(1).txt](https://github.com/user-attachments/files/16533131/_homeassistant_logs.1.txt)

No problem if restart

**Comment by davesmeghead** [comment]
Hi,
Please try 0.9.6.20
Dave

**Comment by davesmeghead** [comment]
Hi
I've just uploaded a dev_B0 release to github.

You can download it here
https://github.com/davesmeghead/visonic/tree/dev_b0

Select the green code and then download zip.

You then need to go to your Home Assistant config directory (where the log file is located) and go into custom_components, replace the visonic directory with the visonic directory in the zip file.

Restart Home Assistant

Dave

**Comment by open1999** [comment]
I did.

still a problem with reloading the service.

In the log, I separated HA restart and Reload Service 



HA Restart
`
[Panel Settings] Downloading panel settings

[sendPdu] **Sending Command (I'm Alive Message To Panel)    waiting for message response**

[sendPdu] **Sending Command (Download Data Set)    waiting for message response ['0X3F']**

[sendPdu] Sending Command (Download Data Set)    waiting for message response ['0X2', '0X3F']`

Reload Service
`[Panel Settings] Downloading panel settings

[sendPdu] Sending Command (Download Data Set)    waiting for message response ['0X2', '0X3F']`


log
[home-assistant_2024-08-15T21-27-02.600Z.log](https://github.com/user-attachments/files/16630907/home-assistant_2024-08-15T21-27-02.600Z.log)

**Comment by davesmeghead** [comment]
Hi

Taking a look at your zip file, the first time it downloads the EPROM OK, lines 48 to 67.  After you reload, the downloading of the EPROM is corrupted somehow, lines 257 to 278 and I'm not sure why.  I've been rewriting the low level code.

Are you able to download a zipfile from Github and install the code manually?
https://github.com/davesmeghead/visonic/tree/dev_b0

Click Green 'Code' and the Download Zip

I've just uploaded dev_B0 Release on Github, please give it a try

In the background I've been rewriting the low level interaction with the panel to centralise it and make it easier for me to understand and debug.

Thanks for your help
Dave

**Comment by open1999** [comment]
I did with dev_B0 (0.9.7.1)

Always a problem with relaod service.

In the log I marked Restart HA and Reload Service

[home-assistant_2024-08-17T18-27-23.106Z.log.zip](https://github.com/user-attachments/files/16646067/home-assistant_2024-08-17T18-27-23.106Z.log.zip)

**Comment by open1999** [comment]
If I restart HA, after Reload Service and after Restart HA I've 2 news warning "Warning: Trying to re enroll, already tried AA AA and still not successful".

[home-assistant_2024-08-17T20-51-36.825Z.log.zip](https://github.com/user-attachments/files/16646490/home-assistant_2024-08-17T20-51-36.825Z.log.zip)

**Comment by davesmeghead** [comment]
Thanks for the logs and the info, really really helpful. 

The 1st log file, initial startup looks OK, it has a problem on reload as you say.  Getting the data from the panel EPROM fails with these:
```
[_validatePDU] Not valid packet, CRC failed
```
I'm not sure why the panel doesn't like it and it may just be a quirk of your panel.  The only thing I can think of is to include a delay on restart so it gives the panel more time between stopping and starting, I don't think it will make a difference but I can think of a way to do it if you want to test it.  Maybe change this line in pyvisonic.py   that should increase the number of seconds after sending the panel the INIT command before it's allowed to continue.
```
   "MSG_INIT"         : VisonicCommand(convertByteArray('AB 0A 00 01 00 00 00 00 00 00 00 43'), None   ,  True, False,  FULL, 3.0, "Init PowerLink Connection" ),
```
To this, change 3 to let's try 9, or maybe longer but not too long as then some of the timeouts in the remainder of the program kick-in and flag as problems.
```
   "MSG_INIT"         : VisonicCommand(convertByteArray('AB 0A 00 01 00 00 00 00 00 00 00 43'), None   ,  True, False,  FULL, 9.0, "Init PowerLink Connection" ),

```

The 2nd one, 20-51-36 looks good, nothing wrong that I spotted.  The Warning is a hangover from me leaving a statement in that  was using during my testing with Home Assistant, so I could see timing between the Integration and the Entities, you can ignore the Warning.

I've just uploaded latest to Github, dev_B0 with these release notes
Updated New Sequencer for EPROM Download and Enrol
Updated triggering control of Motion/Camera Sensors (may not work if not in the UK as it uses UTC timezone and I've only tested here in the UK)
All time sources/values have a timezone associated with them.

Give it a go please if you can
Thanks
Dave

**Comment by open1999** [comment]
ok.
I test tomorrow.

**Comment by open1999** [comment]
2 logs with the last B0 and pyvisonic modified

1st : Restart and Reload with .... "3.0, "Init PowerLink Connection"

[Time3_restart_reload.zip](https://github.com/user-attachments/files/16653360/Time3_restart_reload.zip)

2nd : Restart and Reload with...  "9.0, "Init PowerLink Connection"

[Time9_restart_reload.zip](https://github.com/user-attachments/files/16653467/Time9_restart_reload.zip)

**Comment by davesmeghead** [comment]
Hi,  I've taken a look through the Time9 log file and it hasn't helped, it's just the same.

However, I believe that it's a problem with your setup, perhaps not doing something with the USB or I'm not sure what else.
I conclude this as it is definitely missing data on receive and the panel is ignoring some of the commends sent to it as if they are corrupted in some way.  Let me give you an example, and I'm going to get detailed and technical so brace yourself.

This is line 761, I've replaced some of the data with `<lots of data>` as it's largely irrelevant.
```
[data receiver] Warning : Construction of zero length incoming packet validation failed - Message = 0d 02 fd 0d 3f 80 01 80 <lots of data> 9b 0a  checksum calcs 0X8E
```

So the following is an acknowledge message, it is sent by the panel to tell me that it's received a command and it has been understood
```
0d 02 fd 0a
```
All messages start with an 0d and finish with an 0a
The content of the EPROM data has a similar pattern
```
0d 3f 80 01 80 <lots of data> 9b 0a
```
With your line 761 my software did not receive the 0a at the end of the acknowledge and tried to interpret the whole thing as a single message and failed, it does not understand the message, this is correct as the data in line 761 is not valid.

I've spotted a few other examples like 915
```
[handle_msgtype3F] Invalid data block length, Received: 127, Expected: 128
```
The programme expected to receive 128 bytes from the panel but only received 127, there is a missing byte not received from your panel.

If I put this evidence together with the fact that the first time (before you reload) it runs perfectly
- Line 75 it tries the first time and gets an `[handle_msgtype08] Access Denied`   this is normal, wrong Download Code
- It tries again with the next default download code and succeeds. 
 
Most Important, there are no errors, no missing data, it is a perfect EPROM download sequence.  I checked all your other log files and it's exactly the same.  Perfect the first time, missing data after you reload the integration.   When I checked your other log files there is missing data after you reload, I just didn't understand the relevance until now.

The only conclusion I can make is that either:
- You have a USB connection problem, probably software driver that gets corrupt.
- The Integration runs faster after a reload and that gives the problem

The only way to test the 2nd bullet is to:
- Disable the Integration in the settings in Home Assistant
- Restart Home Assistant and leave it for a while to make sure it has started and the CPU/memory loads settle down
- Enable the Integration

This will let the Integration start as fast as it can, in a similar way to it being restarted.
I'm assuming that since you know how to reload then you know hot to disable and enable it.

Do not restart the integration, zip up and upload the log file please.

**Comment by open1999** [comment]
Ok, I understand the problem.

I did the test.

Disable the Integration /RESTART HA / Wait 5 min (CPU 0.1%) / Enable the integration

After, I did a new disable/wait/enable and same problem

[home-assistant_2024-08-20T23-33-26.571Z.log.zip](https://github.com/user-attachments/files/16683491/home-assistant_2024-08-20T23-33-26.571Z.log.zip)

**Comment by open1999** [comment]
I think it's USB

I did :

A/
1 /Restart HA
2/ Disable the Integration
3/ Enable the integration

=> problem like reload

B/
1 /Restart HA
2/ Disable the Integration
3/ on linux, usbreset 067b:2303 (my controller USB)
3/ Enable the integration

=> no problem

**Comment by davesmeghead** [comment]
If you're convinced that it's a USB problem specific to your setup then can we close this Issue?

**Comment by open1999** [comment]
For "infinite loop" it's ok.

With last version on B0 we have "unavailable" and I have automation to restart HA when Alarm is unvalaible.

It is possible that we have a small problem with opening/closing the USB/serial port or initializing variables when restarting Visonic in HA.
