### ISSUE TITLE
Language-template for upload

### ISSUE THREAD

**Issue by exetico** [davesmeghead/visonic#14]
Hi

I would just like to hear, if you have made a template or so, for uploading new languages?

Else, i guess i would just try and follow the same guidance, as:
https://github.com/davesmeghead/visonic/pull/10

I just spend multiple hours with my alarm. and by accident, i found this component for HA, which are far better than everything else, i've seen.

So, a bit thumbs up from my end.

_I would like to translate it to Danish (DA)_... :-)

**Comment by davesmeghead** [comment]
If you're willing to have a go then yes please, in the same way as olijouve translated it to French.  There are 8 structures in pyvisonic.py for you to translate, you should spot them easily but if you have problems then let me know. Try to use "official/formal" translation rather than more local words and it keeps it generic for everyone.
