### ISSUE TITLE
Connectivity with a PowerMaster 30 with PowerLink3 IP Module

### ISSUE THREAD

**Issue by prime23-gareth** [davesmeghead/visonic#20]
Hi Dave, I've had a PowerMaster 30 system with PowerLink3 IP Module running for a few years. I use the Visonic Go app on my iPhone to control it. 
I've just recently installed Home Assistant and downloaded your visonic integration. I've tried using the integrated settings but I'm struggling with how to tell it the IP address and port of the IP Module.
I've also tried using the configuration.yaml settings where you can enter those details but I was unable to find out the port. 
I can clearly see my alarm system on my network with its allocated static IP address.
My gut feeling from your docs is that this won't work natively with a PowerLink3 IP Connection. I have to force it into some kind of serial mode as per the wiki?  I don't want to lose access via my iPhone / VisonicGo app so I'm reluctant to change anything on the unit.
Are you able to confirm my assumptions that this may not be possible without modifications or new physical serial connections to the alarm unit?

Cheers,
Gareth.

**Comment by davesmeghead** [comment]
Hi,
You would need to remove your Powerlink 3 hardware and stop using it (and the visonic app), replacing it with a different device that costs around £10. 

From what I understand:
1. You cannot force a powerlink 3 module to be a simple serial passthrough device.  
2. Your Powerlink 3 connects to the RS232 port in your panel. Only 1 device can connect to this at a time although there is a dual RS232 module available that might work to connect both but I'm not aware of anyone trying this.

So your gut feeling is right but you'd need to replace your powerlink 3 hardware (unless you try the visonic dual RS232 but that's a cost risk that the powerlink3 and the new device for HA may not work together).

I assume that you have wired ethernet to your panel so it would be really easy to set up the new hardware. If not there are wifi (wireless) options as well.

I'm going to close this issue here but if you want to discuss it further and buy and set up the new hardware then create a post on the main HA forum [here](https://community.home-assistant.io/t/visonic-powermax-and-powermaster-component/55949/1293). Other users and I can then help you out further

Cheers
Dave
