### ISSUE TITLE
Does the Visonic RS-232 Adapter Kit work with your integration?

### ISSUE THREAD

**Issue by maxwell-01** [davesmeghead/visonic#30]
Hello,
Looking at purchasing the PowerMaster 33 and wanted to integrate it with Home Assistant to save doubling up on sensors. Your wiki speaks a lot about **not** using the Visonic RS-232 Adapter Kit, but I'd like to know whether the integration works using Visonic RS-232 Adapter Kit into home assistant?
Thanks!

**Comment by davesmeghead** [comment]
The panel itself has TTL logic levels for its RS232 connector.  The Visonic RS-232 Adapter Kit converts the TTL logic levels to proper RS232 voltage levels (and I think it inverts the logic i.e. a logic 1 is -12v).  So it depends on what you buy to interface your panel with your Home Assistant.  If you buy a USB adaptor then you need to check whether the RS232 is TTL or proper +/- voltage.  If you buy something like a Wemos D1 R2 or something like a USR-TCP232-E2 then they use TTL logic levels and you do not need the Visonic RS-232 Adapter Kit.
Hope this helps, anything further then please post in the forum instead of here please
Thanks and goodluck
