### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by phoenix-blue** [davesmeghead/visonic#62]
I have more and more often the problem that after an reboot of HA the powermax pro not can be found in HA
(Integration Suspended - No data from the panel)

Where to start to check/solve the problem?
When I use the same rs232/usb converter direct in the pc to communicate with the visonic software it's normal working.

**Comment by davesmeghead** [comment]
Capture a log file and upload it to pastebin with a link and I'll take a look.  The log file I need is after the reboot of HA when the integration suspends.

**Comment by phoenix-blue** [comment]
Maybe an noob question, how can I greate an usefull log file?

**Comment by phoenix-blue** [comment]
I have upload the log file -> https://pastebin.com/sKgMmW3k
Alarm panel is connected direct with an serial port (/dev/ttyS3) but i have the same issue when i use an USB-RS232 converter.

And when I remove the integration and install it back it's working, but after an reboot it's not communicate anymore.
note: codes are set in the pastbin to 0000

**Comment by davesmeghead** [comment]
This is a weird one.  From the log file it is making a connection to a USB device but that device does not send any data in response to the panel commands that the integration sends.  Might more than 1 USB device be grabbing /dev/ttyS3 ?
It could also be the USB driver failing and restarting

Unplugging all other USB devices may be a good test but this in itself is not conclusive.

**Comment by dansh1n** [comment]
I also have a problem (ntegration Suspended - No data from the panel)
But this problem occurs only on versions since 0.7.0.3, on version 0.7.0.2 there is no such problem. So far I have remained on version 0.7.0.2.

**Comment by davesmeghead** [comment]
Hi, can you upgrade to the latest version 0.8.1.0 and if you still have a problem then upload a log file to pastebin please. I can then have a proper look to see what is going on.  If I can narrow it down then I can do code diffs between the versions.

**Comment by Sudo-Rob** [comment]
I've had a similar issue when updating the OS.  It turned out to be a reassignment of the USB logical to physical port.  Currently, I'm running HA OS, but I've used Ubuntu and Debian.  It's been quite a while since I experienced the issue, so I can't remember which OS had the problem.  What's the configuration of the operating environment having the issue?

Just now, I've looked at the Host log ([http://homeassistant.local:8123/config/logs](http://homeassistant.local:8123/config/logs)), but since I'm using a Z-wave stick, there's no apparent way to discriminate which device is connected to which logical port.  The obvious difference between the two ports would've been the baud rate, but I see no change of the baud rate in any of the logs after the boot, which shows the defaults.  If I could figure out how to use the `setserial` command ([https://linux.die.net/man/8/setserial](https://linux.die.net/man/8/setserial)), it might be revealing.

Here's a link to the issue:  [https://community.home-assistant.io/t/failed-to-start-the-z-wave-js-add-on/340913/7](https://community.home-assistant.io/t/failed-to-start-the-z-wave-js-add-on/340913/7)

**Comment by dansh1n** [comment]
> Hi, can you upgrade to the latest version 0.8.1.0 and if you still have a problem then upload a log file to pastebin please. I can then have a proper look to see what is going on. If I can narrow it down then I can do code diffs between the versions.

https://dropmefiles.com/63l8E

**Comment by dansh1n** [comment]
I have the problem on version 0.8.2.1.

`2022-10-23 20:29:41.497 ERROR (MainThread) [homeassistant] Error doing job: Fatal error: protocol.data_received() call failed.
Traceback (most recent call last):
File "/opt/lib/python3.10/asyncio/selector_events.py", line 868, in _read_ready__data_received
File "/opt/var/lib/homeassistant/custom_components/visonic/pyvisonic.py", line 1875, in data_received
self._handle_received_byte(databyte)
File "/opt/var/lib/homeassistant/custom_components/visonic/pyvisonic.py", line 1958, in _handle_received_byte
self._processReceivedMessage(ackneeded=self.pmCurrentPDU.ackneeded, data=self.ReceiveData)
File "/opt/var/lib/homeassistant/custom_components/visonic/pyvisonic.py", line 2053, in _processReceivedMessage
self.packet_callback(data)
File "/opt/var/lib/homeassistant/custom_components/visonic/pyvisonic.py", line 3053, in _processReceivedPacket
pushChange = self.handle_msgtypeB0(packet[2:-2])
File "/opt/var/lib/homeassistant/custom_components/visonic/pyvisonic.py", line 4132, in handle_msgtypeB0
self._sendCommand("MSG_PM_1", opt="ZONE_STAT24") # This asks the panel to send 03 04 messages
TypeError: ProtocolBase._sendCommand() got an unexpected keyword argument 'opt'
2022-10-23 20:29:41.605 ERROR (MainThread) [custom_components.visonic.pyvisonic] ERROR Connection Lost : disconnected because the Ethernet/USB connection was externally terminated.
2022-10-23 20:29:41.623 ERROR (MainThread) [custom_components.visonic.pyvisonic] ERROR Connection Lost : disconnected due to exception ProtocolBase._sendCommand() got an unexpected keyword argument 'opt'
2022-10-23 20:29:46.654 ERROR (MainThread) [custom_components.visonic.pyvisonic] Calling Exception handler.
2022-10-23 20:29:56.860 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Panel 0 for select
Traceback (most recent call last):
File "/opt/lib/python3.10/site-packages/homeassistant/config_entries.py", line 496, in async_unload
File "/opt/lib/python3.10/site-packages/homeassistant/components/select/__init__.py", line 66, in async_unload_entry
File "/opt/lib/python3.10/site-packages/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
ValueError: Config entry was never loaded!
2022-10-23 20:29:56.879 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Panel 0 for binary_sensor
Traceback (most recent call last):
File "/opt/lib/python3.10/site-packages/homeassistant/config_entries.py", line 496, in async_unload
File "/opt/lib/python3.10/site-packages/homeassistant/components/binary_sensor/__init__.py", line 173, in async_unload_entry
File "/opt/lib/python3.10/site-packages/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
ValueError: Config entry was never loaded!`

**Comment by davesmeghead** [comment]
I think it's to do with the processing of the B0 messages. This is experimental stuff and doesn't really help with the state of the sensors etc, at least not yet.
Can you reinstall version 0.8.2.1 and set up this integration so it runs. Then go back to the integrations page in HA, and for this integration select "Configure" and then find the settings page with "Enable B0 message processing (PowerMaster Panels only)" and make sure it's unticked. Let me know if it was ticked ot not.  Then click submit.  This page is only shown after he integration is set up and I know that it's a PowerMaster panel type.

**Comment by dansh1n** [comment]
I also noticed a problem with the water USER code in the settings if the code starts with "0", for example 0123

**Comment by davesmeghead** [comment]
Yeah I know about that, I wrote this explanation on the wiki:

For the Override Code
- Set it to 0 when not in use, this represents "No" in the tables below
- The GUI will only allow numbers from 0 to 9999, if your override/user code starts with zero(s) then just miss them out i.e. enter 34 for code 0034

It's a problem wth HA internals. I can either do it like this ot have a "free text" field where the user could type anything of any length.  I know it's not ideal but it's the best I can do in HA at the moment.

**Comment by davesmeghead** [comment]
I've spotted the problem in the experimental code and if you turn off B0 processing it at least won't execute that code so it should get further.

**Comment by dansh1n** [comment]
removed, as you said, the B0 setting, the integration really worked. I will be watching her.

**Comment by davesmeghead** [comment]
OK that's good to know, is it OK to close this issue as resolved?  If you have further issues then just open another.

**Comment by dansh1n** [comment]
10 minutes passed and the problem recurred

**Comment by davesmeghead** [comment]
I'm going to need to see another log file, preferably from initial start up to and including the problem, espcially if it's only 10 minutes then it won't be too large a file

**Comment by davesmeghead** [comment]
If you find the time to try this, make sure you're using the latest version from Github / HACS please

**Comment by dansh1n** [comment]
After one more reinstallation and reboot of HASS, with B0 disabled, the connection problem does not make itself felt, although from time to time the integration loses connection with the panel, but it is reconect itself.

**Comment by phoenix-blue** [comment]
I have update the last version to 8.2.3,but I'm not able to load the integrations list when I have installed this update.
When I use 8.2.2 I can reload the integration list.

Log HA:

`Logger: homeassistant.components.websocket_api.http.connection
Source: loader.py:287
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:50:42 (1 occurrences)
Last logged: 18:50:42

[140645587542192] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 755, in handle_integration_descriptions
    connection.send_result(msg["id"], await async_get_integration_descriptions(hass))
  File "/usr/src/homeassistant/homeassistant/loader.py", line 287, in async_get_integration_descriptions
    custom_flows[integration.integration_type][integration.domain] = metadata
KeyError: 'hub' `

**Comment by davesmeghead** [comment]
After following the HA instruction [here](https://developers.home-assistant.io/docs/creating_integration_manifest/) to add the integration_type to the manifest file, this causes hassfest and the integration to fail. I have reported this in the development forums [here](https://community.home-assistant.io/t/hassfest-failing-on-custom-integration-due-to-integration-type-in-manifest/479789).
This update simply removes the integration_type entry from the manifest file.

**Comment by davesmeghead** [comment]
I'm closing this issue, please feel free to open an new issue for other problems or suggestions.
