### ISSUE TITLE
LOST BBA CONNECTION

### ISSUE THREAD

**Issue by louisdcmr** [davesmeghead/visonic#69]
Hello, i have a problem.
I have connect my alarm to my raspberry pi with a usb to ttl module, and it work perfectly but sometimes (about once a day) my alarm (powermax pro part) show me a defauly (lost com bba) and in HA all of entities show "unknow" to resolve it i have to restart tge intégration and it’s very problematic !
Do you have a solution ?
Sorry for my english i’m french ;)

thanks !

**Comment by davesmeghead** [comment]
Thats OK, your English is much better than my French :)

It could be many different things.
The first thing to check is whether it is a problem with the Visonic Integration, with Home Assistant or with the Raspberry Pi / Operating System.
In the Home Assistant log file (you can view this from within Home Assistant) can you see this error?
Go to Settings, System and then Logs.
```
ERROR Connection Lost : disconnected because the Ethernet/USB connection was externally terminated.
```
If you can see this then the problem is nothing to do with this integration or Home Assistant.  It is the Raspberry Pi Linux Operating System that is terminating the connection. In this case I'm not really going to be much help, other than to say that it may be another service in linux trying to access the USB device and you probably need to prevent this service starting.

If you do not see this error then I'm going to need more information...... it could be the Integration or HA.
Have you turned on logging in Home Assistant?  The instructions to turn on logging are on the wiki [here](https://github.com/davesmeghead/visonic/wiki#logger-settings).  Then please upload the log file to pastebin/dropbox and leave a link here.  If you see this in the log file. As it only happens once per day then I only need the part of the log file with the disconnection and not the whole log file. Good luck.
