### ISSUE TITLE
Entity name wrong in events

### ISSUE THREAD

**Issue by herwinjan** [davesmeghead/visonic#95]
In the latest version the entity id which is  events is wrong:

Event gives back: binary_sensor.visonic_z04
Read sensor entity is : binary_sensor.visonic_p1_z04

For example, the OpenZoned automation is not working.

**Comment by Joao-Sousa-71** [comment]
I had that issue a few months ago and it is related with panel autonumber. Please see this:

[https://github.com/davesmeghead/visonic/issues/79](url)

There is zip with a  __init__.py that will fix your problem.

**Comment by davesmeghead** [comment]
Hi,
It could be the panel numbering problem so i'd be interested to know the version of the integration that you're using?
Are you using the latest version?   I removed autonumbering and so that should not be causing problems now.

If you are using the latest version then I'd like to see a log file please (as setup [here](https://github.com/davesmeghead/visonic/wiki#logger-settings) on my wiki page).
If anyone else sees this post, if you report a problem/bug then please upload a log file, even if it's just a fragment that illustrates the issue.  Only then can I look in to the problem.
D

**Comment by davesmeghead** [comment]
Hi,
I'll close this issue, if there are further problems then please create a new issue, thanks
